from __future__ import annotations

from typing import Any, Literal

from google.cloud import bigquery

STATE_FRESH = "fresh"
STATE_STALE = "stale"
STATE_MISSING = "missing"
STATE_INSUFFICIENT_SAMPLE = "insufficient_sample"
STATE_UNAVAILABLE = "unavailable"
FULL_SEASON_TYPES = ("Regular Season", "Playoffs")

CompareWindow = Literal["last_3", "last_5", "last_7", "prior_5", "last_10"]
CompareFocus = Literal["balanced", "scoring", "playmaking", "defense"]

COMPARE_WINDOW_CONFIG: dict[CompareWindow, dict[str, Any]] = {
    "last_3": {"label": "Last 3", "expected_games": 3},
    "last_5": {"label": "Last 5", "expected_games": 5},
    "last_7": {"label": "Last 7", "expected_games": 7},
    "prior_5": {"label": "Prior 5", "expected_games": 5},
    "last_10": {"label": "Last 10", "expected_games": 10},
}

COMPARE_METRIC_LABELS: dict[str, str] = {
    "fantasy_proxy_score": "Box Score Index",
    "avg_min": "Minutes",
    "avg_pts": "PTS",
    "avg_reb": "REB",
    "avg_ast": "AST",
    "avg_stl": "STL",
    "avg_blk": "BLK",
    "avg_fg3m": "3PM",
    "avg_tov": "TOV",
}

COMPARE_FOCUS_CONFIG: dict[CompareFocus, dict[str, Any]] = {
    "balanced": {
        "label": "Balanced",
        "description": "Keeps the full stat mix in the default read order.",
        "metric_keys": [
            "fantasy_proxy_score",
            "avg_min",
            "avg_pts",
            "avg_reb",
            "avg_ast",
            "avg_stl",
            "avg_blk",
            "avg_fg3m",
            "avg_tov",
        ],
    },
    "scoring": {
        "label": "Scoring",
        "description": "Pushes scoring volume and shot-making to the top of the comparison.",
        "metric_keys": [
            "fantasy_proxy_score",
            "avg_pts",
            "avg_fg3m",
            "avg_min",
            "avg_ast",
            "avg_reb",
            "avg_stl",
            "avg_blk",
            "avg_tov",
        ],
    },
    "playmaking": {
        "label": "Playmaking",
        "description": "Prioritizes creation load first, then supporting scoring context.",
        "metric_keys": [
            "avg_ast",
            "avg_min",
            "avg_tov",
            "fantasy_proxy_score",
            "avg_pts",
            "avg_reb",
            "avg_stl",
            "avg_blk",
            "avg_fg3m",
        ],
    },
    "defense": {
        "label": "Defense",
        "description": "Highlights defensive events and rebounding before offense-first stats.",
        "metric_keys": [
            "avg_stl",
            "avg_blk",
            "avg_reb",
            "fantasy_proxy_score",
            "avg_min",
            "avg_pts",
            "avg_ast",
            "avg_fg3m",
            "avg_tov",
        ],
    },
}

SIMILARITY_RESULT_LIMIT = 6
SIMILARITY_FEATURE_COLUMNS = [
    "season_avg_pts",
    "season_avg_fga",
    "season_fg_pct",
    "season_ts_pct",
    "season_fg3a_rate",
    "season_fta_rate",
    "season_ast_to_tov",
    "team_points_contribution_rate",
    "team_fga_contribution_rate",
    "team_ast_contribution_rate",
    "team_tov_contribution_rate",
    "team_offense_contribution_rate",
    "team_reb_contribution_rate",
    "team_stl_contribution_rate",
    "team_blk_contribution_rate",
    "team_defense_contribution_rate",
    "shot_rim_rate",
    "shot_paint_non_ra_rate",
    "shot_midrange_rate",
    "shot_corner3_rate",
    "shot_above_break3_rate",
    "shot_rim_fg_pct",
    "shot_corner3_fg_pct",
    "season_avg_reb",
    "season_avg_ast",
    "season_avg_stl",
    "season_avg_blk",
    "season_avg_fg3m",
    "season_avg_tov",
    "season_avg_min",
    "height_inches",
    "weight_lbs",
    "season_exp",
    "recent_pts",
    "recent_reb",
    "recent_ast",
    "recent_stl",
    "recent_blk",
    "recent_fg3m",
    "recent_tov",
    "recent_min",
    "recent_points_share_of_team",
    "recent_points_share_of_game",
    "minutes_delta_vs_season",
    "second_half_pts_delta",
    "second_half_min_delta",
    "second_half_ts_delta",
]

SIMILARITY_FEATURE_WEIGHTS: dict[str, float] = {
    feature_name: 1.0 for feature_name in SIMILARITY_FEATURE_COLUMNS
}

SIMILARITY_TRAIT_LABELS: dict[str, str] = {
    "season_avg_pts": "scoring volume",
    "season_avg_fga": "shot volume",
    "season_fg_pct": "field-goal efficiency",
    "season_ts_pct": "true shooting",
    "season_fg3a_rate": "three-point diet",
    "season_fta_rate": "rim pressure",
    "season_ast_to_tov": "ball security",
    "team_points_contribution_rate": "team scoring share",
    "team_fga_contribution_rate": "team shot share",
    "team_ast_contribution_rate": "team assist share",
    "team_tov_contribution_rate": "team turnover load",
    "team_offense_contribution_rate": "team offense ownership",
    "team_reb_contribution_rate": "team rebounding share",
    "team_stl_contribution_rate": "team steal share",
    "team_blk_contribution_rate": "team block share",
    "team_defense_contribution_rate": "team defensive event share",
    "shot_rim_rate": "rim shot diet",
    "shot_paint_non_ra_rate": "paint shot diet",
    "shot_midrange_rate": "midrange diet",
    "shot_corner3_rate": "corner-three diet",
    "shot_above_break3_rate": "above-break three diet",
    "shot_rim_fg_pct": "rim finishing",
    "shot_corner3_fg_pct": "corner-three efficiency",
    "season_avg_reb": "rebounding",
    "season_avg_ast": "playmaking",
    "season_avg_stl": "steals pressure",
    "season_avg_blk": "rim protection",
    "season_avg_fg3m": "three-point volume",
    "season_avg_min": "minutes load",
    "height_inches": "height",
    "weight_lbs": "frame strength",
    "season_exp": "experience",
    "recent_points_share_of_team": "usage share",
    "recent_points_share_of_game": "game scoring share",
    "minutes_delta_vs_season": "minutes trend",
    "second_half_pts_delta": "second-half scoring growth",
    "second_half_min_delta": "second-half role growth",
    "second_half_ts_delta": "second-half efficiency growth",
}

STAT_PERCENTILE_CONFIG: tuple[dict[str, str], ...] = (
    {
        "key": "pts",
        "label": "PTS",
        "average_field": "season_avg_pts",
        "percentile_field": "pts_percentile",
        "baseline_field": "league_avg_pts",
        "direction": "higher",
    },
    {
        "key": "reb",
        "label": "REB",
        "average_field": "season_avg_reb",
        "percentile_field": "reb_percentile",
        "baseline_field": "league_avg_reb",
        "direction": "higher",
    },
    {
        "key": "ast",
        "label": "AST",
        "average_field": "season_avg_ast",
        "percentile_field": "ast_percentile",
        "baseline_field": "league_avg_ast",
        "direction": "higher",
    },
    {
        "key": "stl",
        "label": "STL",
        "average_field": "season_avg_stl",
        "percentile_field": "stl_percentile",
        "baseline_field": "league_avg_stl",
        "direction": "higher",
    },
    {
        "key": "blk",
        "label": "BLK",
        "average_field": "season_avg_blk",
        "percentile_field": "blk_percentile",
        "baseline_field": "league_avg_blk",
        "direction": "higher",
    },
    {
        "key": "tov",
        "label": "Ball Security",
        "average_field": "season_avg_tov",
        "percentile_field": "tov_percentile",
        "baseline_field": "league_avg_tov",
        "direction": "lower",
    },
)

TREND_STAT_ORDER = {
    "PTS": 1,
    "REB": 2,
    "AST": 3,
    "STL": 4,
    "BLK": 5,
    "TOV": 6,
    "MIN": 7,
    "FG%": 8,
    "FT%": 9,
    "3PM": 10,
    "FANTASY_POINTS_SIMPLE": 11,
}

RECENT_PERFORMANCE_STAT_CONFIG: tuple[dict[str, Any], ...] = (
    {"key": "pts", "label": "PTS"},
    {"key": "reb", "label": "REB"},
    {"key": "ast", "label": "AST"},
    {"key": "stl", "label": "STL"},
    {"key": "blk", "label": "BLK"},
    {"key": "min", "label": "MIN"},
    {"key": "fg_pct", "label": "FG%", "format": "percent"},
    {"key": "ft_pct", "label": "FT%", "format": "percent"},
    {"key": "fg3m", "label": "3PM"},
)
RECENT_PERFORMANCE_PERCENT_KEYS = {"fg_pct", "ft_pct"}
RECENT_PERFORMANCE_DETAIL_HYDRATE_KEYS = ("min", "fg_pct", "ft_pct", "fg3m")

RECENT_PERFORMANCE_TABLE_FIELDS: tuple[bigquery.SchemaField, ...] = (
    bigquery.SchemaField("season", "STRING"),
    bigquery.SchemaField("season_type", "STRING"),
    bigquery.SchemaField("game_id", "STRING"),
    bigquery.SchemaField("game_date", "DATE"),
    bigquery.SchemaField("teams", "STRING"),
    bigquery.SchemaField("game_matchup", "STRING"),
    bigquery.SchemaField("home_team_abbr", "STRING"),
    bigquery.SchemaField("away_team_abbr", "STRING"),
    bigquery.SchemaField("home_team_pts", "INTEGER"),
    bigquery.SchemaField("away_team_pts", "INTEGER"),
    bigquery.SchemaField("players_played", "INTEGER"),
    bigquery.SchemaField("player_id", "INTEGER"),
    bigquery.SchemaField("player_name", "STRING"),
    bigquery.SchemaField("team_abbr", "STRING"),
    bigquery.SchemaField("opponent_abbr", "STRING"),
    bigquery.SchemaField("home_away", "STRING"),
    bigquery.SchemaField("matchup", "STRING"),
    bigquery.SchemaField("wl", "STRING"),
    bigquery.SchemaField("min", "FLOAT"),
    bigquery.SchemaField("pts", "FLOAT"),
    bigquery.SchemaField("reb", "FLOAT"),
    bigquery.SchemaField("ast", "FLOAT"),
    bigquery.SchemaField("stl", "FLOAT"),
    bigquery.SchemaField("blk", "FLOAT"),
    bigquery.SchemaField("fg_pct", "FLOAT"),
    bigquery.SchemaField("ft_pct", "FLOAT"),
    bigquery.SchemaField("fg3m", "FLOAT"),
    bigquery.SchemaField("games_sampled", "INTEGER"),
    bigquery.SchemaField("avg_pts", "FLOAT"),
    bigquery.SchemaField("avg_reb", "FLOAT"),
    bigquery.SchemaField("avg_ast", "FLOAT"),
    bigquery.SchemaField("avg_stl", "FLOAT"),
    bigquery.SchemaField("avg_blk", "FLOAT"),
    bigquery.SchemaField("avg_min", "FLOAT"),
    bigquery.SchemaField("avg_fg_pct", "FLOAT"),
    bigquery.SchemaField("avg_ft_pct", "FLOAT"),
    bigquery.SchemaField("avg_fg3m", "FLOAT"),
    bigquery.SchemaField("pts_delta", "FLOAT"),
    bigquery.SchemaField("reb_delta", "FLOAT"),
    bigquery.SchemaField("ast_delta", "FLOAT"),
    bigquery.SchemaField("stl_delta", "FLOAT"),
    bigquery.SchemaField("blk_delta", "FLOAT"),
    bigquery.SchemaField("min_delta", "FLOAT"),
    bigquery.SchemaField("fg_pct_delta", "FLOAT"),
    bigquery.SchemaField("ft_pct_delta", "FLOAT"),
    bigquery.SchemaField("fg3m_delta", "FLOAT"),
    bigquery.SchemaField("pts_delta_pct", "FLOAT"),
    bigquery.SchemaField("reb_delta_pct", "FLOAT"),
    bigquery.SchemaField("ast_delta_pct", "FLOAT"),
    bigquery.SchemaField("stl_delta_pct", "FLOAT"),
    bigquery.SchemaField("blk_delta_pct", "FLOAT"),
    bigquery.SchemaField("min_delta_pct", "FLOAT"),
    bigquery.SchemaField("fg_pct_delta_pct", "FLOAT"),
    bigquery.SchemaField("ft_pct_delta_pct", "FLOAT"),
    bigquery.SchemaField("fg3m_delta_pct", "FLOAT"),
    bigquery.SchemaField("pts_p10", "FLOAT"),
    bigquery.SchemaField("pts_p25", "FLOAT"),
    bigquery.SchemaField("pts_p50", "FLOAT"),
    bigquery.SchemaField("pts_p75", "FLOAT"),
    bigquery.SchemaField("pts_p90", "FLOAT"),
    bigquery.SchemaField("pts_percentile", "FLOAT"),
    bigquery.SchemaField("reb_p10", "FLOAT"),
    bigquery.SchemaField("reb_p25", "FLOAT"),
    bigquery.SchemaField("reb_p50", "FLOAT"),
    bigquery.SchemaField("reb_p75", "FLOAT"),
    bigquery.SchemaField("reb_p90", "FLOAT"),
    bigquery.SchemaField("reb_percentile", "FLOAT"),
    bigquery.SchemaField("ast_p10", "FLOAT"),
    bigquery.SchemaField("ast_p25", "FLOAT"),
    bigquery.SchemaField("ast_p50", "FLOAT"),
    bigquery.SchemaField("ast_p75", "FLOAT"),
    bigquery.SchemaField("ast_p90", "FLOAT"),
    bigquery.SchemaField("ast_percentile", "FLOAT"),
    bigquery.SchemaField("stl_p10", "FLOAT"),
    bigquery.SchemaField("stl_p25", "FLOAT"),
    bigquery.SchemaField("stl_p50", "FLOAT"),
    bigquery.SchemaField("stl_p75", "FLOAT"),
    bigquery.SchemaField("stl_p90", "FLOAT"),
    bigquery.SchemaField("stl_percentile", "FLOAT"),
    bigquery.SchemaField("blk_p10", "FLOAT"),
    bigquery.SchemaField("blk_p25", "FLOAT"),
    bigquery.SchemaField("blk_p50", "FLOAT"),
    bigquery.SchemaField("blk_p75", "FLOAT"),
    bigquery.SchemaField("blk_p90", "FLOAT"),
    bigquery.SchemaField("blk_percentile", "FLOAT"),
    bigquery.SchemaField("min_p10", "FLOAT"),
    bigquery.SchemaField("min_p25", "FLOAT"),
    bigquery.SchemaField("min_p50", "FLOAT"),
    bigquery.SchemaField("min_p75", "FLOAT"),
    bigquery.SchemaField("min_p90", "FLOAT"),
    bigquery.SchemaField("min_percentile", "FLOAT"),
    bigquery.SchemaField("fg_pct_p10", "FLOAT"),
    bigquery.SchemaField("fg_pct_p25", "FLOAT"),
    bigquery.SchemaField("fg_pct_p50", "FLOAT"),
    bigquery.SchemaField("fg_pct_p75", "FLOAT"),
    bigquery.SchemaField("fg_pct_p90", "FLOAT"),
    bigquery.SchemaField("fg_pct_percentile", "FLOAT"),
    bigquery.SchemaField("ft_pct_p10", "FLOAT"),
    bigquery.SchemaField("ft_pct_p25", "FLOAT"),
    bigquery.SchemaField("ft_pct_p50", "FLOAT"),
    bigquery.SchemaField("ft_pct_p75", "FLOAT"),
    bigquery.SchemaField("ft_pct_p90", "FLOAT"),
    bigquery.SchemaField("ft_pct_percentile", "FLOAT"),
    bigquery.SchemaField("fg3m_p10", "FLOAT"),
    bigquery.SchemaField("fg3m_p25", "FLOAT"),
    bigquery.SchemaField("fg3m_p50", "FLOAT"),
    bigquery.SchemaField("fg3m_p75", "FLOAT"),
    bigquery.SchemaField("fg3m_p90", "FLOAT"),
    bigquery.SchemaField("fg3m_percentile", "FLOAT"),
    bigquery.SchemaField("performance_score", "FLOAT"),
    bigquery.SchemaField("performance_status", "STRING"),
    bigquery.SchemaField("above_count", "INTEGER"),
    bigquery.SchemaField("below_count", "INTEGER"),
    bigquery.SchemaField("date_rank", "INTEGER"),
    bigquery.SchemaField("game_rank", "INTEGER"),
    bigquery.SchemaField("trend_points_json", "STRING"),
)
RECENT_PERFORMANCE_TABLE_ROW_CACHE_TTL_SECONDS = 900
RECENT_PERFORMANCE_TABLE_ROW_MAX_RESULTS = 5000

AGENT_METRIC_LEADER_CONFIG: dict[str, dict[str, str]] = {
    "pts": {
        "label": "PTS",
        "column": "avg_pts",
        "percentile_column": "pts_percentile",
        "order": "DESC",
    },
    "reb": {
        "label": "REB",
        "column": "avg_reb",
        "percentile_column": "reb_percentile",
        "order": "DESC",
    },
    "ast": {
        "label": "AST",
        "column": "avg_ast",
        "percentile_column": "ast_percentile",
        "order": "DESC",
    },
    "stl": {
        "label": "STL",
        "column": "avg_stl",
        "percentile_column": "stl_percentile",
        "order": "DESC",
    },
    "blk": {
        "label": "BLK",
        "column": "avg_blk",
        "percentile_column": "blk_percentile",
        "order": "DESC",
    },
    "tov": {
        "label": "TOV",
        "column": "avg_tov",
        "percentile_column": "tov_percentile",
        "order": "ASC",
    },
    "fg3m": {
        "label": "3PM",
        "column": "avg_fg3m",
        "percentile_column": "NULL",
        "order": "DESC",
    },
    "min": {
        "label": "MIN",
        "column": "avg_min",
        "percentile_column": "NULL",
        "order": "DESC",
    },
    "fantasy_points_simple": {
        "label": "BSI",
        "column": "avg_fantasy_points_simple",
        "percentile_column": "NULL",
        "order": "DESC",
    },
}

AGENT_METRIC_COLUMN_MAP: dict[str, str] = {
    "pts": "avg_pts",
    "reb": "avg_reb",
    "ast": "avg_ast",
    "stl": "avg_stl",
    "blk": "avg_blk",
    "fg3m": "avg_fg3m",
    "tov": "avg_tov",
    "min": "avg_min",
    "fantasy_points_simple": "avg_fantasy_points_simple",
}
