"""Render local human reviews without model calls."""

import html
import json
import re
from pathlib import Path

from app.agent.reporting_evidence import validate_response
from scripts.reporting_artifacts import load_run, read
from scripts.reporting_contracts import validate_batch

REPORT_TEMPLATE = (
    Path(__file__).parent / "templates/reporting_review.html"
).read_text()


def render_page(*, template=REPORT_TEMPLATE, **values):
    """Fill named slots once; callers escape text and explicitly compose HTML."""
    defaults = {
        "TITLE": "NBA Stats Desk · Evidence review",
        "EYEBROW": "NBA Stats Desk / research preview",
        "HEADING": "Can the answer earn your trust?",
        "DESCRIPTION": "10 responses grounded in warehouse statistics and curated reporting. Generated by GPT-5.6 Luna; evaluated by GPT-5.6 Terra. Read each response, inspect its evidence, then record your decision. Terra's assessment stays collapsed until you choose to reveal it.",
        "FOOTNOTE": "Original responses are preserved; human notes do not alter model outputs.",
        "STORAGE_PREFIX": "nba-evidence-review-",
        "EXPORT_NAME": "nba-evidence-human-review.json",
    }
    defaults["EXTRA_LINKS"] = ""
    defaults.update(values)
    return re.sub(r"__([A-Z_]+?)__", lambda m: defaults[m[1]], template)


def report(args):
    manifest, prepared = load_run(args.run_dir)
    responses = read(args.run_dir / "generation.json")
    evaluations = read(args.run_dir / "evaluation.json")
    expected = [p["case"]["id"] for p in prepared]
    validate_batch(responses, "responses", expected)
    validate_batch(evaluations, "evaluations", expected)
    notes_path = args.run_dir / "review-notes.json"
    review_notes = read(notes_path) if notes_path.exists() else []
    baseline_path = args.run_dir / "baseline-answers.json"
    baseline = (
        {r["case_id"]: r for r in read(baseline_path)["responses"]}
        if baseline_path.exists()
        else {}
    )
    if any(note["case_id"] not in expected for note in review_notes):
        raise ValueError("Review note references an unknown case")
    e = html.escape
    sections, markdown = (
        [],
        [
            "# NBA evidence review\n",
            "Generator: GPT-5.6 Luna · Evaluator: GPT-5.6 Terra · Human decision: pending\n",
        ],
    )
    for p, response, evaluation in zip(
        prepared, responses["responses"], evaluations["evaluations"], strict=True
    ):
        case, bundle = p["case"], p["bundle"]
        case_id = case["id"]
        sources = {s["id"]: s for s in bundle["reporting"]["passages"]}
        claims = []
        markdown.extend(
            [f"\n## {case_id}: {case['player_name']}\n", case["question"] + "\n"]
        )
        for claim in response["claims"]:
            links = " ".join(
                f'<a href="{e(sources[k]["url"], quote=True)}" target="_blank" rel="noopener noreferrer">{e(k)}</a>'
                if k in sources
                else f'<a href="#{case_id}-stats">{e(k)}</a>'
                for k in claim["evidence_ids"]
            )
            claims.append(
                f'<p><span class="kind">{e(claim["kind"].replace("_", " "))}</span>{e(claim["text"])} <span class="citations">{links}</span></p>'
            )
            refs = " ".join(
                f"[{k}]({sources[k]['url']})" if k in sources else f"[{k}]"
                for k in claim["evidence_ids"]
            )
            markdown.append(claim["text"] + " " + refs + "\n")
        rows = "".join(
            f"<tr><td>{e(m['label'])}<br><small>{e(m.get('unit', 'per game'))}; change: {e(m.get('change_unit', 'per game'))}</small></td><td>{fmt(m['previous'])}</td><td>{fmt(m['current'])}</td><td>{fmt(m['change'])}</td><td>{m.get('previous_missing_games', 0)} / {m['missing_games']}</td></tr>"
            for m in bundle["statistics"]["metrics"]
        )
        source_html = (
            "".join(
                f'<article class="source"><a href="{e(s["url"], quote=True)}" target="_blank" rel="noopener noreferrer">{s["id"]} · {e(s["title"])}</a><p class="muted">{e(s["author"])} · displayed update {s["version_available_date"]} · event {s["event_start"]}–{s["event_end"]}</p><p>{e(s["summary"])}</p><small>Curated paraphrase, not a quotation.</small></article>'
                for s in sources.values()
            )
            or "<p>No relevant reporting in this curated corpus.</p>"
        )
        issues = (
            "".join(
                f"<li><strong>{e(i['severity'])} · claim {i['claim_index'] + 1 if i['claim_index'] >= 0 else 'missing'}:</strong> {e(i['reason'])}<br>Suggested fix: {e(i['suggested_fix'])}</li>"
                for i in evaluation["issues"]
            )
            or "<li>No issues identified by Terra.</li>"
        )
        scores = " · ".join(
            f"{k.replace('_', ' ')}: {v}/2" for k, v in evaluation["scores"].items()
        )
        errors = validate_response(bundle, response)
        scope = bundle["scope"]
        context_html = ""
        for key, title in (
            ("opponent", "Opponent context"),
            ("teammate", "Teammate comparison"),
        ):
            if key in bundle["statistics"]:
                context_html += f'<details><summary>{title} — descriptive evidence and coverage</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px">{e(json.dumps(bundle["statistics"][key], indent=2))}</pre></details>'
        context_html += (
            '<details><summary>Shooting counts behind the percentages</summary><pre style="white-space:pre-wrap;font-size:11px">'
            + e(
                json.dumps(
                    {
                        m["label"]: m["components"]
                        for m in bundle["statistics"]["metrics"]
                        if "components" in m
                    },
                    indent=2,
                )
            )
            + "</pre></details>"
        )
        old_html = ""
        if case_id in baseline:
            old_html = (
                "<details><summary>Compare original answer before this milestone</summary>"
                + "".join(
                    "<p>" + e(c["text"]) + "</p>" for c in baseline[case_id]["claims"]
                )
                + "</details>"
            )
        sections.append(f'''<section id="{case_id}" data-case="{case_id}"><div class="eyebrow">{case_id} / {e(case["category"])}</div><h2>{e(case["player_name"])}</h2><p class="question">{e(case["question"])}</p><div class="scope">{scope["previous_start"]}–{scope["previous_end"]} → {scope["start"]}–{scope["end"]} · {e(scope["phase"])}</div>{old_html}<div class="answer">{"".join(claims)}</div>
<details><summary>Inspect statistics and reporting</summary><div id="{case_id}-stats"><p>Recorded appearances: {bundle["statistics"]["appearances"]["previous"]} → {bundle["statistics"]["appearances"]["current"]}. Count averages are per recorded appearance; shooting percentages and per-36 rates use their own denominators.</p><p>Observed teams: {e(", ".join(bundle["statistics"]["teams"]["previous"]) or "None")} → {e(", ".join(bundle["statistics"]["teams"]["current"]) or "None")}.</p><table><thead><tr><th>Metric</th><th>Previous</th><th>Current</th><th>Change</th><th>Missing games<br>Previous / current</th></tr></thead><tbody>{rows}</tbody></table><p class="muted">Reference values show three decimal places; generated prose rounds to one. Changes are calculated from unrounded rates.</p></div>{source_html}<p class="muted">Reporting mode: {scope["reporting_mode"]}; cutoff {scope["reporting_cutoff"]}. Stats are retrospectively corrected.</p><p class="muted">Structural checks: {e(", ".join(errors) if errors else "Passed. This does not verify semantic support.")}</p></details>
{context_html}<details class="judge"><summary>Reveal Terra evaluation</summary><strong>{e(evaluation["verdict"].upper())} · {sum(evaluation["scores"].values())}/10</strong><p>{e(evaluation["summary"])}</p><p class="muted">{e(scores)}</p><ul>{issues}</ul></details>
<div class="human"><label>Your decision <select data-field="decision"><option value="">Not reviewed</option><option>Accept</option><option>Revise</option><option>Reject</option></select></label><label>Your notes <textarea data-field="notes" rows="3" placeholder="What worked? What should change?"></textarea></label></div></section>''')
        markdown.extend(
            [
                "\n### Terra evaluation\n",
                f"{evaluation['verdict']} · {sum(evaluation['scores'].values())}/10\n",
                evaluation["summary"] + "\n",
            ]
        )
        markdown.extend(
            f"- {i['severity']}: {i['reason']} Fix: {i['suggested_fix']}\n"
            for i in evaluation["issues"]
        )
        markdown.append("\nHuman decision: pending\n")
        for note in review_notes:
            if note["case_id"] == case_id:
                message = note["message"]
                annotation = f'<aside class="source"><strong>Additional verification — separate from Terra</strong><p>{e(message)}</p></aside>'
                sections[-1] = sections[-1].replace(
                    '<details class="judge">', annotation + '<details class="judge">', 1
                )
                markdown.append("\nAdditional verification: " + message + "\n")
    nav = "".join(
        f'<a href="#{p["case"]["id"]}">{p["case"]["id"]} {e(p["case"]["player_name"])}<br><small>{e(p["case"]["previous_start"][:7])} → {e(p["case"]["start"][:7])}</small></a>'
        for p in prepared
    )
    limits = " ".join(manifest["limits"])
    seasons = ", ".join(sorted({s for p in prepared for s in p["case"]["seasons"]}))
    extra_links = ""
    if (args.run_dir / "generation-metadata.json").exists():
        from scripts.reporting_step_review import render_step_review

        render_step_review(
            args.run_dir,
            manifest,
            prepared,
            responses["responses"],
            evaluations["evaluations"],
            REPORT_TEMPLATE,
        )
        extra_links = '<a href="step-review.html" style="color:#dceab8;margin-right:20px">Review pipeline steps and tokens</a>'
    document = render_page(
        NAV=nav,
        SECTIONS="".join(sections),
        LIMITS=e(limits),
        RUN_ID=manifest["prepared_sha256"],
        TITLE=f"NBA Stats Desk · Evidence review · {e(seasons)}",
        EYEBROW=f"NBA Stats Desk / research preview / {e(seasons)}",
        EXTRA_LINKS=extra_links,
    )
    (args.run_dir / "review.html").write_text(document)
    (args.run_dir / "review.md").write_text(
        "\n".join(markdown) + "\n\nLimitations: " + limits + "\n"
    )
    print(args.run_dir / "review.html")


def fmt(value):
    return "Unavailable" if value is None else f"{value:.3f}"
